#
# Libraries to build
#
LIBRARY += 

#
# .cc that define main
#
TARGET += test/unit/schd/test_th_pool.cc		\
	  test/unit/schd/test_th_message.cc		\
	  test/unit/schd/test_call_later.cc		\
	  test/unit/net/transport/test_tcp.cc		\
	  test/unit/net/rpc/test_rpc.cc			\
	  test/unit/fs/test_aio.cc			\
	  test/perf/fs/bmark_aio.cc			\
	  test/perf/net/bmark_tcp.cc			\

#
# .cc
#
SRCS += 

#
# .pyx
#
# PYX += test/unit/py/basic_test.pyx
