#
# Libraries to build
#
LIBRARY += 

#
# .cc that define main
#
TARGET += test/test_th_pool.cc	    \
          test/test_th_message.cc	    \
          test/test_tcp.cc		    \
          test/test_aio.cc		    \
	  test/test_rpc.cc		    \

#
# .cc
#
SRCS += 
