#
# Libraries to build
#
LIBRARY += 

#
# .cc that define main
#
TARGET += test/unit/schd/test_th_pool.cc		\
	  test/unit/schd/test_th_message.cc		\
	  test/unit/net/test_tcp.cc			\
	  test/unit/net/test_rpc.cc			\
	  test/unit/fs/test_aio.cc			\

#
# .cc
#
SRCS += 
