#
# Libraries to build
#
LIBRARY += core                 \
           core/net             \
           core/fs              \

#
# .cc that define main
#
TARGET +=

#
# .cc
#
SRCS += core/thread-pool.cc     \
        core/net/epoll.cc       \
	core/net/rpc.cc		\
        core/net/tcp-linux.cc   \
        core/fs/aio-linux.cc    \
