#
# Libraries to build
#
LIBRARY += core

#
# .cc that define main
#
TARGET +=

#
# .cc
#
SRCS += core/actor.cc\

#	core/assert.cc \
#        core/logger.cc \
#        core/actor.cc \
#        core/scheduler.cc \
#        core/epollset.cc \
#        core/tcpserver.cc \
#        core/linux_aio.cc
