#
# Libraries to build
#
LIBRARY += core/net \
           core/fs

#
# .cc that define main
#
TARGET +=

#
# .cc
#
SRCS += core/net/epoll.cc \
        core/net/tcp-linux.cc \
        core/fs/aio-linux.cc

#	core/assert.cc \
#        core/logger.cc \
#        core/actor.cc \
#        core/scheduler.cc \
#        core/epollset.cc \
#        core/tcpserver.cc \
#        core/linux_aio.cc
