#
# Libraries to build
#
LIBRARY +=  src			    \
	    src/net		    \
	    src/fs		    \

#
# .cc that define main
#
TARGET +=

#
# .cc
#
SRCS += src/schd/thread-pool.cc	    \
	src/net/epoll/epoll.cc	    \
	src/net/rpc/bblocks/rpc-data.cc	    \
	src/net/transport/tcp-linux.cc	    \
	src/net/rpc/rpc.cc		    \
	src/fs/aio-linux.cc	    \
